"""rename address

Revision ID: 80305ea302bc
Revises: d612b8c29866
Create Date: 2024-10-02 17:35:30.003284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80305ea302bc'
down_revision = 'd612b8c29866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')
